#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${CODERCLAW_INSTALL_E2E_IMAGE:-${CODERCLAW_INSTALL_E2E_IMAGE:-coderclaw-install-e2e:local}}"
INSTALL_URL="${CODERCLAW_INSTALL_URL:-${CODERCLAW_INSTALL_URL:-https://coderclaw.ai/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
CODERCLAW_E2E_MODELS="${CODERCLAW_E2E_MODELS:-${CODERCLAW_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e CODERCLAW_INSTALL_URL="$INSTALL_URL" \
  -e CODERCLAW_INSTALL_TAG="${CODERCLAW_INSTALL_TAG:-${CODERCLAW_INSTALL_TAG:-latest}}" \
  -e CODERCLAW_E2E_MODELS="$CODERCLAW_E2E_MODELS" \
  -e CODERCLAW_INSTALL_E2E_PREVIOUS="${CODERCLAW_INSTALL_E2E_PREVIOUS:-${CODERCLAW_INSTALL_E2E_PREVIOUS:-}}" \
  -e CODERCLAW_INSTALL_E2E_SKIP_PREVIOUS="${CODERCLAW_INSTALL_E2E_SKIP_PREVIOUS:-${CODERCLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
