export const browserCoreExamples = [
  "coderclaw browser status",
  "coderclaw browser start",
  "coderclaw browser stop",
  "coderclaw browser tabs",
  "coderclaw browser open https://example.com",
  "coderclaw browser focus abcd1234",
  "coderclaw browser close abcd1234",
  "coderclaw browser screenshot",
  "coderclaw browser screenshot --full-page",
  "coderclaw browser screenshot --ref 12",
  "coderclaw browser snapshot",
  "coderclaw browser snapshot --format aria --limit 200",
  "coderclaw browser snapshot --efficient",
  "coderclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "coderclaw browser navigate https://example.com",
  "coderclaw browser resize 1280 720",
  "coderclaw browser click 12 --double",
  'coderclaw browser type 23 "hello" --submit',
  "coderclaw browser press Enter",
  "coderclaw browser hover 44",
  "coderclaw browser drag 10 11",
  "coderclaw browser select 9 OptionA OptionB",
  "coderclaw browser upload /tmp/coderclaw/uploads/file.pdf",
  'coderclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "coderclaw browser dialog --accept",
  'coderclaw browser wait --text "Done"',
  "coderclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "coderclaw browser console --level error",
  "coderclaw browser pdf",
];
